# NanosOS cmake/xtensa_esp32s3.cmake - Xtensa LX7 cross-compile toolchain
cmake_minimum_required(VERSION 3.20)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR xtensa-esp32s3)
set(PFX "xtensa-esp32s3-elf-")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
find_program(CMAKE_C_COMPILER   "${PFX}gcc")
find_program(CMAKE_CXX_COMPILER "${PFX}g++")
find_program(CMAKE_ASM_COMPILER "${PFX}gcc")
find_program(CMAKE_OBJCOPY      "${PFX}objcopy")
find_program(CMAKE_SIZE         "${PFX}size")
find_program(CMAKE_NM           "${PFX}nm")
if(NOT CMAKE_C_COMPILER)
    message(FATAL_ERROR "Xtensa toolchain not found. Source: . $IDF_PATH/export.sh")
endif()
string(JOIN " " ARCH "-mlongcalls" "-mtext-section-literals" "-mfix-esp32-psram-cache-issue")
set(CMAKE_C_FLAGS_INIT   "${ARCH}")
set(CMAKE_CXX_FLAGS_INIT "${ARCH} -fno-exceptions -fno-rtti")
set(CMAKE_ASM_FLAGS_INIT "${ARCH}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-nostdlib -Wl,--gc-sections")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
message(STATUS "Toolchain: ${CMAKE_C_COMPILER}")
